apiVersion: v1 #k8s is enxtensible - we can add our own custom objects. this specifies the set of objects we want k8s to look at.
kind: Pod # the type of object we want to create
metadata: # config options for the object we are about to create
  name: posts-pod  # the name of the pod k8s is gonna give
spec: # attributes we want to apply to the object we want to create
  containers:
    - name: posts
      image: jeldikk/posts:0.0.1 # by default without version information. k8s will reach out of internet to dockerhub